# Server
server.port=8080

# ===== CHANGE THIS to your actual college email domain =====
# e.g. if your email is name@rvce.edu.in, put @rvce.edu.in
app.college-domain=@rvce.edu.in

# Database (matches docker-compose below)
spring.datasource.url=jdbc:postgresql://localhost:5432/lostfound
spring.datasource.username=lostfound
spring.datasource.password=lostfound
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT (used from Step 2) - change the secret to something long & random
app.jwt.secret=Bd2kIVuJubruwZaLVKHiUXolWKleJwZK
app.jwt.expiration-ms=86400000

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.org.springframework.security=DEBUG