services:
  db:
    image: postgres:latest
    container_name: lostfound-db
    environment:
      POSTGRES_DB: lostfound
      POSTGRES_USER: lostfound
      POSTGRES_PASSWORD: lostfound
    ports:
      - "5432:5432"
    volumes:
      - lostfound_pgdata:/var/lib/postgresql #removed /data because of new postgres

volumes:
  lostfound_pgdata: